// Command xorgen generates internal/config/secrets_obfuscated.go by
// XOR-encoding secrets from environment variables with a random 32-byte key.
//
// Usage:
//
//	SD_BOT_TOKEN=... SD_CHANNEL_ID=... xorgen [-out secrets_obfuscated.go]
//
// The generated file is tagged with //go:build obfuscate so it is only
// included when building with -tags obfuscate. Otherwise secrets_off.go
// (empty stubs) is compiled, and config.Load() falls back to ldflags/env.
package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"os"
)

var outPath = flag.String("out", "internal/config/secrets_obfuscated.go", "output file path")

func main() {
	flag.Parse()

	wd, _ := os.Getwd()
	fmt.Fprintf(os.Stderr, "[xorgen] working dir: %s\n", wd)

	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		fmt.Fprintf(os.Stderr, "[xorgen] crypto/rand: %v\n", err)
		os.Exit(1)
	}

	// XOR-encode each secret. Missing env vars produce empty []byte{}.
	xorEncodePair := func(envKey string) []byte {
		plain := os.Getenv(envKey)
		if plain == "" {
			fmt.Fprintf(os.Stderr, "[xorgen] warning: %s empty — agent will fallback to ldflags/env\n", envKey)
			return []byte{}
		}
		data := []byte(plain)
		out := make([]byte, len(data))
		for i := range data {
			out[i] = data[i] ^ key[i%len(key)]
		}
		return out
	}

	botToken := xorEncodePair("SD_BOT_TOKEN")
	channelID := xorEncodePair("SD_CHANNEL_ID")
	targetID := xorEncodePair("SD_TARGET_ID")
	aesKey := xorEncodePair("SD_AES_KEY_HEX")

	content := fmt.Sprintf(`// Code generated by xorgen; DO NOT EDIT.

//go:build obfuscate

package config

var (
	xorKey       = %#v
	xorBotToken  = %#v
	xorChannelID = %#v
	xorTargetID  = %#v
	xorAESKeyHex = %#v
)
`, key, botToken, channelID, targetID, aesKey)

	if err := os.WriteFile(*outPath, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "[xorgen] write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "[xorgen] wrote %s (%d bytes)\n", *outPath, len(content))
}
